# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise_api', '0015_auto_20151130_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingModification',
        ),
    ]
