# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise_api', '0016_delete_pendingmodification'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='default',
            field=models.CharField(blank=True, max_length=255, verbose_name='default'),
        ),
    ]
