# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise_api', '0017_setting_default'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DBVersion',
        ),
    ]
