# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise_api', '0018_delete_dbversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openstreetmapelement',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='superlachaisecategory',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='superlachaisepoi',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='wikidataentry',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='wikimediacommonscategory',
            name='deleted',
        ),
    ]
