# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise_api', '0019_auto_20151213_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikimediacommonsfile',
            old_name='thumbnail_url',
            new_name='thumbnail_url_512',
        ),
        migrations.RemoveField(
            model_name='wikimediacommonsfile',
            name='original_url',
        ),
        migrations.AddField(
            model_name='wikimediacommonsfile',
            name='thumbnail_url_1024',
            field=models.CharField(blank=True, max_length=500, verbose_name='thumbnail url'),
        ),
        migrations.AddField(
            model_name='wikimediacommonsfile',
            name='thumbnail_url_2048',
            field=models.CharField(blank=True, max_length=500, verbose_name='thumbnail url'),
        ),
    ]
