# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise_api', '0020_auto_20160417_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikimediacommonsfile',
            name='thumbnail_url_1024',
        ),
        migrations.RemoveField(
            model_name='wikimediacommonsfile',
            name='thumbnail_url_2048',
        ),
        migrations.RemoveField(
            model_name='wikimediacommonsfile',
            name='thumbnail_url_512',
        ),
        migrations.AddField(
            model_name='wikimediacommonsfile',
            name='url_1024px',
            field=models.CharField(blank=True, max_length=500, verbose_name='url 1024px'),
        ),
        migrations.AddField(
            model_name='wikimediacommonsfile',
            name='url_2048px',
            field=models.CharField(blank=True, max_length=500, verbose_name='url 2048px'),
        ),
        migrations.AddField(
            model_name='wikimediacommonsfile',
            name='url_512px',
            field=models.CharField(blank=True, max_length=500, verbose_name='url 512px'),
        ),
    ]
