# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise_api', '0022_wikimediacommonsfile_attribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikimediacommonsfile',
            name='attribution',
        ),
        migrations.AddField(
            model_name='wikimediacommonsfile',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='wikimediacommonsfile',
            name='license',
            field=models.CharField(blank=True, max_length=255, verbose_name='license'),
        ),
    ]
